package gestionClients;

import javax.swing.*;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.UIManager;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Desktop;
import java.util.ArrayList;
import java.net.URI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenoovo
 */
public class Main extends javax.swing.JFrame {
    private static DBConnect conn = DBConnect.getInstance();
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        titleBar = new javax.swing.JPanel();
        closeBtn = new javax.swing.JLabel();
        reduceBtn = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        homeSideBtn = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        clientSideBtn = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        productSideBtn = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        orderSideBtn = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        adminSideBtn = new javax.swing.JPanel();
        ind_5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        socialMediaPnl = new javax.swing.JPanel();
        gitHubBtn = new javax.swing.JLabel();
        linkedInBtn = new javax.swing.JLabel();
        facebookBtn = new javax.swing.JLabel();
        instagramBtn = new javax.swing.JLabel();
        xBtn = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        homePnl = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clientPnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        crudClients = new javax.swing.JPanel();
        addClient = new javax.swing.JButton();
        deleteClient = new javax.swing.JButton();
        modifyClient = new javax.swing.JButton();
        searchClient = new javax.swing.JButton();
        reloadClientsTableBtn = new javax.swing.JLabel();
        productPnl = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        productsTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        crudProducts = new javax.swing.JPanel();
        addProduct = new javax.swing.JButton();
        modifyProduct = new javax.swing.JButton();
        searchProduct = new javax.swing.JButton();
        reloadProductsTableBtn = new javax.swing.JLabel();
        orderPnl = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        orderTable = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        crudOrders = new javax.swing.JPanel();
        addOrder = new javax.swing.JButton();
        deleteOrder = new javax.swing.JButton();
        modifyOrder = new javax.swing.JButton();
        searchOrder = new javax.swing.JButton();
        reloadOrdersTableBtn = new javax.swing.JLabel();
        adminPnl = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        adminsTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        crudAdmin = new javax.swing.JPanel();
        addAdmin = new javax.swing.JButton();
        deleteAdmin = new javax.swing.JButton();
        modifyAdmin = new javax.swing.JButton();
        searchAdmin = new javax.swing.JButton();
        reloadAdminsTableBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleBar.setBackground(new java.awt.Color(22, 42, 57));
        titleBar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 96)));
        titleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleBarMouseDragged(evt);
            }
        });
        titleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleBarMousePressed(evt);
            }
        });

        closeBtn.setBackground(new java.awt.Color(22, 42, 57));
        closeBtn.setForeground(new java.awt.Color(255, 255, 255));
        closeBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/closeWhite.png"))); // NOI18N
        closeBtn.setOpaque(true);
        closeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeBtnMouseExited(evt);
            }
        });

        reduceBtn.setBackground(new java.awt.Color(22, 42, 57));
        reduceBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reduceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reduceWhite.png"))); // NOI18N
        reduceBtn.setOpaque(true);
        reduceBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reduceBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reduceBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reduceBtnMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop28.png"))); // NOI18N
        jLabel13.setText("Gestion Clients");

        javax.swing.GroupLayout titleBarLayout = new javax.swing.GroupLayout(titleBar);
        titleBar.setLayout(titleBarLayout);
        titleBarLayout.setHorizontalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleBarLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 902, Short.MAX_VALUE)
                .addComponent(reduceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(closeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        titleBarLayout.setVerticalGroup(
            titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleBarLayout.createSequentialGroup()
                .addGroup(titleBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(closeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reduceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bg.add(titleBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 30));

        sidePanel.setBackground(new java.awt.Color(33, 63, 96));
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop.png"))); // NOI18N
        jLabel5.setText("Gestion Shop");
        sidePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 70));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        sidePanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 10));

        homeSideBtn.setBackground(new java.awt.Color(22, 42, 57));
        homeSideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homeSideBtnMousePressed(evt);
            }
        });

        ind_1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/acceuil.png"))); // NOI18N
        jLabel1.setText("  Acceuil");
        jLabel1.setAlignmentY(0.0F);

        javax.swing.GroupLayout homeSideBtnLayout = new javax.swing.GroupLayout(homeSideBtn);
        homeSideBtn.setLayout(homeSideBtnLayout);
        homeSideBtnLayout.setHorizontalGroup(
            homeSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeSideBtnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        homeSideBtnLayout.setVerticalGroup(
            homeSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeSideBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ind_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(homeSideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 50));

        clientSideBtn.setBackground(new java.awt.Color(33, 63, 96));
        clientSideBtn.setPreferredSize(new java.awt.Dimension(260, 50));
        clientSideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clientSideBtnMousePressed(evt);
            }
        });

        ind_2.setBackground(new java.awt.Color(255, 255, 255));
        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(4, 0));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        jLabel2.setText("  Clients");
        jLabel2.setAlignmentY(0.0F);

        javax.swing.GroupLayout clientSideBtnLayout = new javax.swing.GroupLayout(clientSideBtn);
        clientSideBtn.setLayout(clientSideBtnLayout);
        clientSideBtnLayout.setHorizontalGroup(
            clientSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientSideBtnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        clientSideBtnLayout.setVerticalGroup(
            clientSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientSideBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ind_2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sidePanel.add(clientSideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 250, -1));

        productSideBtn.setBackground(new java.awt.Color(33, 63, 96));
        productSideBtn.setPreferredSize(new java.awt.Dimension(260, 50));
        productSideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                productSideBtnMousePressed(evt);
            }
        });

        ind_3.setBackground(new java.awt.Color(255, 255, 255));
        ind_3.setOpaque(false);

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produits.png"))); // NOI18N
        jLabel4.setText("  Produits");
        jLabel4.setAlignmentY(0.0F);

        javax.swing.GroupLayout productSideBtnLayout = new javax.swing.GroupLayout(productSideBtn);
        productSideBtn.setLayout(productSideBtnLayout);
        productSideBtnLayout.setHorizontalGroup(
            productSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productSideBtnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        productSideBtnLayout.setVerticalGroup(
            productSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productSideBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ind_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(productSideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 250, -1));

        orderSideBtn.setBackground(new java.awt.Color(33, 63, 96));
        orderSideBtn.setPreferredSize(new java.awt.Dimension(260, 50));
        orderSideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                orderSideBtnMousePressed(evt);
            }
        });

        ind_4.setBackground(new java.awt.Color(255, 255, 255));
        ind_4.setOpaque(false);

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setBackground(new java.awt.Color(33, 63, 96));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/commandes.png"))); // NOI18N
        jLabel3.setText("  Commandes");
        jLabel3.setAlignmentY(0.0F);

        javax.swing.GroupLayout orderSideBtnLayout = new javax.swing.GroupLayout(orderSideBtn);
        orderSideBtn.setLayout(orderSideBtnLayout);
        orderSideBtnLayout.setHorizontalGroup(
            orderSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSideBtnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        orderSideBtnLayout.setVerticalGroup(
            orderSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderSideBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ind_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(orderSideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 250, -1));

        adminSideBtn.setBackground(new java.awt.Color(33, 63, 96));
        adminSideBtn.setPreferredSize(new java.awt.Dimension(260, 50));
        adminSideBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminSideBtnMousePressed(evt);
            }
        });

        ind_5.setBackground(new java.awt.Color(255, 255, 255));
        ind_5.setOpaque(false);

        javax.swing.GroupLayout ind_5Layout = new javax.swing.GroupLayout(ind_5);
        ind_5.setLayout(ind_5Layout);
        ind_5Layout.setHorizontalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_5Layout.setVerticalGroup(
            ind_5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/admin.png"))); // NOI18N
        jLabel6.setText("  Administrateurs");
        jLabel6.setAlignmentY(0.0F);

        javax.swing.GroupLayout adminSideBtnLayout = new javax.swing.GroupLayout(adminSideBtn);
        adminSideBtn.setLayout(adminSideBtnLayout);
        adminSideBtnLayout.setHorizontalGroup(
            adminSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminSideBtnLayout.createSequentialGroup()
                .addComponent(ind_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        adminSideBtnLayout.setVerticalGroup(
            adminSideBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminSideBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(ind_5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        sidePanel.add(adminSideBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 250, -1));

        socialMediaPnl.setLayout(new java.awt.GridLayout(1, 0));

        gitHubBtn.setBackground(new java.awt.Color(22, 42, 57));
        gitHubBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gitHubBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/github38.png"))); // NOI18N
        gitHubBtn.setOpaque(true);
        gitHubBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gitHubBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gitHubBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                gitHubBtnMouseExited(evt);
            }
        });
        socialMediaPnl.add(gitHubBtn);

        linkedInBtn.setBackground(new java.awt.Color(22, 42, 57));
        linkedInBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        linkedInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/linkedin38.png"))); // NOI18N
        linkedInBtn.setOpaque(true);
        linkedInBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                linkedInBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                linkedInBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                linkedInBtnMouseExited(evt);
            }
        });
        socialMediaPnl.add(linkedInBtn);

        facebookBtn.setBackground(new java.awt.Color(22, 42, 57));
        facebookBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        facebookBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/facebook38.png"))); // NOI18N
        facebookBtn.setOpaque(true);
        facebookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                facebookBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                facebookBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                facebookBtnMouseExited(evt);
            }
        });
        socialMediaPnl.add(facebookBtn);

        instagramBtn.setBackground(new java.awt.Color(22, 42, 57));
        instagramBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        instagramBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instagram38.png"))); // NOI18N
        instagramBtn.setOpaque(true);
        instagramBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instagramBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                instagramBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                instagramBtnMouseExited(evt);
            }
        });
        socialMediaPnl.add(instagramBtn);

        xBtn.setBackground(new java.awt.Color(22, 42, 57));
        xBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/x38.png"))); // NOI18N
        xBtn.setOpaque(true);
        xBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                xBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                xBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                xBtnMouseExited(evt);
            }
        });
        socialMediaPnl.add(xBtn);

        sidePanel.add(socialMediaPnl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 542, 250, 50));

        bg.add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 590));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 63, 96)));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePnl.setBackground(new java.awt.Color(255, 255, 255));
        homePnl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePnl.setPreferredSize(new java.awt.Dimension(850, 500));
        homePnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(100, 151, 177));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/java.png"))); // NOI18N
        jLabel11.setText("Swing");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Oracle_logo.png"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Créée par : Adnan Bouzkraoui");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("<html> &nbsp;&nbsp;&nbsp;L'Application de Gestion Shop offre une solution intuitive pour gérer efficacement les informations clients. Avec une interface conviviale basée sur Java Swing, cette application permet aux utilisateurs d'effectuer des opérations essentielles telles que l'ajout, la modification, la recherche, et la suppression de données clients dans une base de données Oracle.</html>");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/shop48.png"))); // NOI18N
        jLabel7.setText("Bienvenu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 631, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        homePnl.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, -1, 440));

        mainPanel.add(homePnl, "home");

        clientPnl.setBackground(new java.awt.Color(255, 255, 255));
        clientPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(100, 151, 177));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Clients");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        clientPnl.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 848, -1));

        clientsTable.setBackground(new java.awt.Color(247, 247, 247));
        List<List> clientsData = conn.getData("CLIENTS");
        List<List> clientsTableRows = clientsData.subList(1, clientsData.size());
        List clientsTableColumns = clientsData.get(0);
        clientsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        clientsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            listListToObjectArray(clientsTableRows),
            listToObjectArray(clientsTableColumns)
        ));
        clientsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clientsTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane2.setViewportView(clientsTable);

        clientPnl.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 848, 400));

        crudClients.setBackground(new java.awt.Color(255, 255, 255));
        crudClients.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 42, 57)));
        crudClients.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addClient.setBackground(new java.awt.Color(100, 151, 177));
        addClient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addClient.setForeground(new java.awt.Color(255, 255, 255));
        addClient.setText("Ajouter");
        addClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addClient.setDisplayedMnemonicIndex(1);
        addClient.setOpaque(true);
        addClient.setPreferredSize(new java.awt.Dimension(113, 32));
        addClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addClientMouseClicked(evt);
            }
        });
        crudClients.add(addClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 40, 130, 40));

        deleteClient.setBackground(new java.awt.Color(100, 151, 177));
        deleteClient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteClient.setForeground(new java.awt.Color(255, 255, 255));
        deleteClient.setText("Supprimer");
        deleteClient.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deleteClient.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deleteClient.setOpaque(true);
        deleteClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteClientMouseClicked(evt);
            }
        });
        crudClients.add(deleteClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 40, 130, 40));

        modifyClient.setBackground(new java.awt.Color(100, 151, 177));
        modifyClient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        modifyClient.setForeground(new java.awt.Color(255, 255, 255));
        modifyClient.setText("Modifier");
        modifyClient.setOpaque(true);
        modifyClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyClientMouseClicked(evt);
            }
        });
        crudClients.add(modifyClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 40, 130, 40));

        searchClient.setBackground(new java.awt.Color(100, 151, 177));
        searchClient.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchClient.setForeground(new java.awt.Color(255, 255, 255));
        searchClient.setText("Rechercher");
        searchClient.setOpaque(true);
        searchClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchClientMouseClicked(evt);
            }
        });
        crudClients.add(searchClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 40, 130, 40));

        reloadClientsTableBtn.setBackground(new java.awt.Color(22, 42, 57));
        reloadClientsTableBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reloadClientsTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload25.png"))); // NOI18N
        reloadClientsTableBtn.setOpaque(true);
        reloadClientsTableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadClientsTableBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reloadClientsTableBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reloadClientsTableBtnMouseExited(evt);
            }
        });
        crudClients.add(reloadClientsTableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 40, 30));

        clientPnl.add(crudClients, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 850, 120));

        mainPanel.add(clientPnl, "client");

        productPnl.setBackground(new java.awt.Color(255, 255, 255));
        productPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productsTable.setBackground(new java.awt.Color(247, 247, 247));
        productsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        productsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        List<List> productsData = conn.getData("PRODUITS");
        List<List> productsTableRows = productsData.subList(1, productsData.size());
        List productsTableColumns = productsData.get(0);
        productsTable.setModel(new javax.swing.table.DefaultTableModel(
            listListToObjectArray(productsTableRows),
            listToObjectArray(productsTableColumns)
        ));
        productsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productsTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane3.setViewportView(productsTable);

        productPnl.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 848, 400));

        jPanel3.setBackground(new java.awt.Color(100, 151, 177));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Produits");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        productPnl.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 848, -1));

        crudProducts.setBackground(new java.awt.Color(255, 255, 255));
        crudProducts.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 42, 57)));
        crudProducts.setLayout(null);

        addProduct.setBackground(new java.awt.Color(100, 151, 177));
        addProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setText("Ajouter");
        addProduct.setOpaque(true);
        addProduct.setPreferredSize(new java.awt.Dimension(113, 32));
        addProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addProductMouseClicked(evt);
            }
        });
        crudProducts.add(addProduct);
        addProduct.setBounds(150, 40, 130, 40);

        modifyProduct.setBackground(new java.awt.Color(100, 151, 177));
        modifyProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        modifyProduct.setForeground(new java.awt.Color(255, 255, 255));
        modifyProduct.setText("Modifier");
        modifyProduct.setOpaque(true);
        modifyProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyProductMouseClicked(evt);
            }
        });
        crudProducts.add(modifyProduct);
        modifyProduct.setBounds(360, 40, 130, 40);

        searchProduct.setBackground(new java.awt.Color(100, 151, 177));
        searchProduct.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchProduct.setForeground(new java.awt.Color(255, 255, 255));
        searchProduct.setText("Rechercher");
        searchProduct.setOpaque(true);
        searchProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchProductMouseClicked(evt);
            }
        });
        crudProducts.add(searchProduct);
        searchProduct.setBounds(570, 40, 130, 40);

        reloadProductsTableBtn.setBackground(new java.awt.Color(22, 42, 57));
        reloadProductsTableBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reloadProductsTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload25.png"))); // NOI18N
        reloadProductsTableBtn.setOpaque(true);
        reloadProductsTableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadProductsTableBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reloadProductsTableBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reloadProductsTableBtnMouseExited(evt);
            }
        });
        crudProducts.add(reloadProductsTableBtn);
        reloadProductsTableBtn.setBounds(810, 0, 40, 30);

        productPnl.add(crudProducts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 850, 120));

        mainPanel.add(productPnl, "product");

        orderPnl.setBackground(new java.awt.Color(255, 255, 255));
        orderPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        orderTable.setBackground(new java.awt.Color(247, 247, 247));
        orderTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        orderTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        List<List> orderData = conn.getData("COMMANDES");
        List<List> orderTableRows = orderData.subList(1, orderData.size());
        List orderTableColumns = orderData.get(0);
        orderTable.setModel(new javax.swing.table.DefaultTableModel(
            listListToObjectArray(orderTableRows),
            listToObjectArray(orderTableColumns)
        ));
        orderTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        orderTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane4.setViewportView(orderTable);

        orderPnl.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 848, 400));

        jPanel4.setBackground(new java.awt.Color(100, 151, 177));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Commandes");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        orderPnl.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 848, -1));

        crudOrders.setBackground(new java.awt.Color(255, 255, 255));
        crudOrders.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 42, 57)));
        crudOrders.setLayout(null);

        addOrder.setBackground(new java.awt.Color(100, 151, 177));
        addOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addOrder.setForeground(new java.awt.Color(255, 255, 255));
        addOrder.setText("Ajouter");
        addOrder.setOpaque(true);
        addOrder.setPreferredSize(new java.awt.Dimension(113, 32));
        addOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addOrderMouseClicked(evt);
            }
        });
        crudOrders.add(addOrder);
        addOrder.setBounds(81, 40, 130, 40);

        deleteOrder.setBackground(new java.awt.Color(100, 151, 177));
        deleteOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteOrder.setForeground(new java.awt.Color(255, 255, 255));
        deleteOrder.setText("Supprimer");
        deleteOrder.setOpaque(true);
        deleteOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteOrderMouseClicked(evt);
            }
        });
        crudOrders.add(deleteOrder);
        deleteOrder.setBounds(267, 40, 130, 40);

        modifyOrder.setBackground(new java.awt.Color(100, 151, 177));
        modifyOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        modifyOrder.setForeground(new java.awt.Color(255, 255, 255));
        modifyOrder.setText("Modifier");
        modifyOrder.setOpaque(true);
        modifyOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyOrderMouseClicked(evt);
            }
        });
        crudOrders.add(modifyOrder);
        modifyOrder.setBounds(453, 40, 130, 40);

        searchOrder.setBackground(new java.awt.Color(100, 151, 177));
        searchOrder.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchOrder.setForeground(new java.awt.Color(255, 255, 255));
        searchOrder.setText("Rechercher");
        searchOrder.setOpaque(true);
        searchOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchOrderMouseClicked(evt);
            }
        });
        crudOrders.add(searchOrder);
        searchOrder.setBounds(639, 40, 130, 40);

        reloadOrdersTableBtn.setBackground(new java.awt.Color(22, 42, 57));
        reloadOrdersTableBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reloadOrdersTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload25.png"))); // NOI18N
        reloadOrdersTableBtn.setOpaque(true);
        reloadOrdersTableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadOrdersTableBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reloadOrdersTableBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reloadOrdersTableBtnMouseExited(evt);
            }
        });
        crudOrders.add(reloadOrdersTableBtn);
        reloadOrdersTableBtn.setBounds(810, 0, 40, 30);

        orderPnl.add(crudOrders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 850, 120));

        mainPanel.add(orderPnl, "order");

        adminPnl.setBackground(new java.awt.Color(255, 255, 255));
        adminPnl.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminsTable.setBackground(new java.awt.Color(247, 247, 247));
        adminsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(187, 187, 187)));
        adminsTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        List<List> adminsData = conn.getData("GESTIONNAIRES");
        List<List> adminsTableRows = adminsData.subList(1, adminsData.size());
        List adminsTableColumns = adminsData.get(0);
        adminsTable.setModel(new javax.swing.table.DefaultTableModel(
            listListToObjectArray(adminsTableRows),
            listToObjectArray(adminsTableColumns)
        ));
        adminsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        adminsTable.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane5.setViewportView(adminsTable);

        adminPnl.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 69, 848, 400));

        jPanel5.setBackground(new java.awt.Color(100, 151, 177));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Administrateurs");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
        );

        adminPnl.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 848, -1));

        crudAdmin.setBackground(new java.awt.Color(255, 255, 255));
        crudAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 42, 57)));
        crudAdmin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        addAdmin.setBackground(new java.awt.Color(100, 151, 177));
        addAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addAdmin.setForeground(new java.awt.Color(255, 255, 255));
        addAdmin.setText("Ajouter");
        addAdmin.setOpaque(true);
        addAdmin.setPreferredSize(new java.awt.Dimension(113, 32));
        addAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addAdminMouseClicked(evt);
            }
        });
        crudAdmin.add(addAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 40, 130, 40));

        deleteAdmin.setBackground(new java.awt.Color(100, 151, 177));
        deleteAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        deleteAdmin.setForeground(new java.awt.Color(255, 255, 255));
        deleteAdmin.setText("Supprimer");
        deleteAdmin.setOpaque(true);
        deleteAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteAdminMouseClicked(evt);
            }
        });
        crudAdmin.add(deleteAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 40, 130, 40));

        modifyAdmin.setBackground(new java.awt.Color(100, 151, 177));
        modifyAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        modifyAdmin.setForeground(new java.awt.Color(255, 255, 255));
        modifyAdmin.setText("Modifier");
        modifyAdmin.setOpaque(true);
        modifyAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyAdminMouseClicked(evt);
            }
        });
        crudAdmin.add(modifyAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 40, 130, 40));

        searchAdmin.setBackground(new java.awt.Color(100, 151, 177));
        searchAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        searchAdmin.setForeground(new java.awt.Color(255, 255, 255));
        searchAdmin.setText("Rechercher");
        searchAdmin.setOpaque(true);
        searchAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchAdminMouseClicked(evt);
            }
        });
        crudAdmin.add(searchAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(639, 40, 130, 40));

        reloadAdminsTableBtn.setBackground(new java.awt.Color(22, 42, 57));
        reloadAdminsTableBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reloadAdminsTableBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reload25.png"))); // NOI18N
        reloadAdminsTableBtn.setOpaque(true);
        reloadAdminsTableBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reloadAdminsTableBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reloadAdminsTableBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reloadAdminsTableBtnMouseExited(evt);
            }
        });
        crudAdmin.add(reloadAdminsTableBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 40, 30));

        adminPnl.add(crudAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 850, 120));

        mainPanel.add(adminPnl, "admin");

        bg.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 850, 590));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void onClick(JPanel panel) {
        panel.setBackground(new java.awt.Color(22,42,57));
    }
    
    private void onLeaveClick(JPanel panel) {
        panel.setBackground(new java.awt.Color(33,63,96));
    }
    private void clientSideBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientSideBtnMousePressed
        onLeaveClick(homeSideBtn);
        onClick(clientSideBtn);
        onLeaveClick(productSideBtn);
        onLeaveClick(orderSideBtn);
        onLeaveClick(adminSideBtn);
        ind_1.setOpaque(false);
        ind_2.setOpaque(true);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
        showPanel("client");
    }//GEN-LAST:event_clientSideBtnMousePressed

    private void homeSideBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeSideBtnMousePressed
        onClick(homeSideBtn);
        onLeaveClick(clientSideBtn);
        onLeaveClick(productSideBtn);
        onLeaveClick(orderSideBtn);
        onLeaveClick(adminSideBtn);
        ind_1.setOpaque(true);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
        showPanel("home");
    }//GEN-LAST:event_homeSideBtnMousePressed

    private void productSideBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_productSideBtnMousePressed
        onLeaveClick(homeSideBtn);
        onLeaveClick(clientSideBtn);
        onClick(productSideBtn);
        onLeaveClick(orderSideBtn);
        onLeaveClick(adminSideBtn);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(true);
        ind_4.setOpaque(false);
        ind_5.setOpaque(false);
        showPanel("product");
    }//GEN-LAST:event_productSideBtnMousePressed

    private void orderSideBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_orderSideBtnMousePressed
        onLeaveClick(homeSideBtn);
        onLeaveClick(clientSideBtn);
        onLeaveClick(productSideBtn);
        onClick(orderSideBtn);
        onLeaveClick(adminSideBtn);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(true);
        ind_5.setOpaque(false);
        showPanel("order");
    }//GEN-LAST:event_orderSideBtnMousePressed

    private void adminSideBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminSideBtnMousePressed
        onLeaveClick(homeSideBtn);
        onLeaveClick(clientSideBtn);
        onLeaveClick(productSideBtn);
        onLeaveClick(orderSideBtn);
        onClick(adminSideBtn);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        ind_5.setOpaque(true);
        showPanel("admin");
    }//GEN-LAST:event_adminSideBtnMousePressed

    private void closeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseClicked
        conn.quitter();
        System.exit(0);
    }//GEN-LAST:event_closeBtnMouseClicked

    private void closeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseEntered
        closeBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_closeBtnMouseEntered

    private void closeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBtnMouseExited
        closeBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_closeBtnMouseExited

    private void reduceBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceBtnMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_reduceBtnMouseClicked

    private void reduceBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceBtnMouseEntered
        reduceBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_reduceBtnMouseEntered

    private void reduceBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reduceBtnMouseExited
        reduceBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_reduceBtnMouseExited
    int xx, xy;
    private void titleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_titleBarMousePressed

    private void titleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleBarMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_titleBarMouseDragged

    private void addClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addClientMouseClicked
        JTextField idField = new JTextField();
        JTextField nomField = new JTextField();
        JTextField prenomField = new JTextField();
        JTextField adresseField = new JTextField();
        JTextField emailField = new JTextField();
        JTextField telField = new JTextField();
        JComponent[] inputs = new JComponent[] {
            new JLabel("ID :"),
            idField,
            new JLabel("NOM :"),
            nomField,
            new JLabel("PRENOM :"),
            prenomField,
            new JLabel("ADRESSE :"),
            adresseField,
            new JLabel("EMAIL :"),
            emailField,
            new JLabel("TELEPHONE :"),
            telField,
        };
        int result = JOptionPane.showConfirmDialog(null, inputs, "Information client", JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            conn.addClient(Integer.parseInt(idField.getText()), nomField.getText(), prenomField.getText(), adresseField.getText(), emailField.getText(), telField.getText());
            updateTable("CLIENTS");
        } else {
            System.out.println("User canceled / closed the dialog, result = " + result);
        }
    }//GEN-LAST:event_addClientMouseClicked

    private void deleteClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteClientMouseClicked
        int index = clientsTable.getSelectedRow();
        if(index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            conn.deleteClient((int) clientsTable.getValueAt(index, 0));
            updateTable("CLIENTS");
        }
    }//GEN-LAST:event_deleteClientMouseClicked

    private void modifyClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyClientMouseClicked
        int index = (int) clientsTable.getSelectedRow();
        if(index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            JTextField idField = new JTextField();
            idField.setText(Integer.toString((int) clientsTable.getValueAt(index, 0)));
            JTextField nomField = new JTextField();
            nomField.setText((String) clientsTable.getValueAt(index, 1));
            JTextField prenomField = new JTextField();
            prenomField.setText((String) clientsTable.getValueAt(index, 2));
            JTextField adresseField = new JTextField();
            adresseField.setText((String) clientsTable.getValueAt(index, 3));
            JTextField emailField = new JTextField();
            emailField.setText((String) clientsTable.getValueAt(index, 4));
            JTextField telField = new JTextField();
            telField.setText((String) clientsTable.getValueAt(index, 5));
            JComponent[] inputs;
            inputs = new JComponent[] {
                new JLabel("ID :"),
                idField,
                new JLabel("NOM :"),
                nomField,
                new JLabel("PRENOM :"),
                prenomField,
                new JLabel("ADRESSE :"),
                adresseField,
                new JLabel("EMAIL :"),
                emailField,
                new JLabel("TELEPHONE :"),
                telField,
            };
            int result = JOptionPane.showConfirmDialog(null, inputs, "Client information", JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                conn.modifyClient(Integer.parseInt(idField.getText()), nomField.getText(), prenomField.getText(), adresseField.getText(), emailField.getText(), telField.getText());
                updateTable("CLIENTS");
            } else {
                System.out.println("User canceled / closed the dialog, result = " + result);
            }
        }
            
    }//GEN-LAST:event_modifyClientMouseClicked

    private void searchClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchClientMouseClicked
        int clientId = Integer.parseInt(JOptionPane.showInputDialog(null, "CLIENT ID:", "Rechercher client", JOptionPane.PLAIN_MESSAGE));
        List<List> data = conn.find("CLIENTS", clientId);
        List<List> TableRows = new ArrayList<>();
        TableRows.add(data.get(1));
        List TableColumns = data.get(0);
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns))); 
    }//GEN-LAST:event_searchClientMouseClicked

    private void reloadClientsTableBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadClientsTableBtnMouseEntered
        reloadClientsTableBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_reloadClientsTableBtnMouseEntered

    private void reloadClientsTableBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadClientsTableBtnMouseExited
        reloadClientsTableBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_reloadClientsTableBtnMouseExited

    private void reloadProductsTableBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadProductsTableBtnMouseEntered
        reloadProductsTableBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_reloadProductsTableBtnMouseEntered

    private void reloadProductsTableBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadProductsTableBtnMouseExited
        reloadProductsTableBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_reloadProductsTableBtnMouseExited

    private void reloadOrdersTableBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadOrdersTableBtnMouseEntered
        reloadProductsTableBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_reloadOrdersTableBtnMouseEntered

    private void reloadOrdersTableBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadOrdersTableBtnMouseExited
        reloadOrdersTableBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_reloadOrdersTableBtnMouseExited

    private void reloadAdminsTableBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadAdminsTableBtnMouseEntered
        reloadAdminsTableBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_reloadAdminsTableBtnMouseEntered

    private void reloadAdminsTableBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadAdminsTableBtnMouseExited
        reloadAdminsTableBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_reloadAdminsTableBtnMouseExited

    private void reloadClientsTableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadClientsTableBtnMouseClicked
        this.updateTable("CLIENTS");
    }//GEN-LAST:event_reloadClientsTableBtnMouseClicked

    private void reloadProductsTableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadProductsTableBtnMouseClicked
        this.updateTable("PRODUITS");
    }//GEN-LAST:event_reloadProductsTableBtnMouseClicked

    private void reloadOrdersTableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadOrdersTableBtnMouseClicked
        this.updateTable("COMMANDES");
    }//GEN-LAST:event_reloadOrdersTableBtnMouseClicked

    private void reloadAdminsTableBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reloadAdminsTableBtnMouseClicked
        this.updateTable("GESTIONNAIRES");
    }//GEN-LAST:event_reloadAdminsTableBtnMouseClicked

    private void addProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addProductMouseClicked
        JTextField idField = new JTextField();
        JTextField nameField = new JTextField();
        JTextField descField = new JTextField();
        JTextField priceField = new JTextField();
        JTextField stockField = new JTextField();
        JComponent[] inputs = new JComponent[] {
            new JLabel("PRODUIT_ID :"),
            idField,
            new JLabel("NOM_PRODUIT :"),
            nameField,
            new JLabel("DESCRIPTION :"),
            descField,
            new JLabel("PRIX :"),
            priceField,
            new JLabel("STOCK :"),
            stockField,
        };
        int result = JOptionPane.showConfirmDialog(null, inputs, "Informations produit", JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            conn.addProduct(Integer.parseInt(idField.getText()), nameField.getText(), descField.getText(), priceField.getText(), Integer.parseInt(stockField.getText()));
            updateTable("PRODUITS");
        } else {
            System.out.println("User canceled / closed the dialog, result = " + result);
        }
    }//GEN-LAST:event_addProductMouseClicked
        
    private void modifyProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyProductMouseClicked
        int index = (int) productsTable.getSelectedRow();
        if(index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            JTextField idField = new JTextField();
            idField.setText(Integer.toString((int) productsTable.getValueAt(index, 0)));
            JTextField nameField = new JTextField();
            nameField.setText((String) productsTable.getValueAt(index, 1));
            JTextField descField = new JTextField();
            descField.setText((String) productsTable.getValueAt(index, 2));
            JTextField priceField = new JTextField();
            priceField.setText((String) productsTable.getValueAt(index, 3));
            JTextField stockField = new JTextField();
            stockField.setText(Integer.toString((int) productsTable.getValueAt(index, 4)));
            JComponent[] inputs = new JComponent[] {
                new JLabel("PRODUIT_ID :"),
                idField,
                new JLabel("NOM_PRODUIT :"),
                nameField,
                new JLabel("DESCRIPTION :"),
                descField,
                new JLabel("PRIX :"),
                priceField,
                new JLabel("STOCK :"),
                stockField,
            };
            int result = JOptionPane.showConfirmDialog(null, inputs, "Informations produit", JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                conn.modifyProduct(Integer.parseInt(idField.getText()), nameField.getText(), descField.getText(), priceField.getText(), Integer.parseInt(stockField.getText()));
                updateTable("PRODUITS");
            } else {
                System.out.println("User canceled / closed the dialog, result = " + result);
            }
        }
    }//GEN-LAST:event_modifyProductMouseClicked

    private void searchProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchProductMouseClicked
        int productId = Integer.parseInt(JOptionPane.showInputDialog(null, "ID PRODUIT :", "Rechercher produit", JOptionPane.PLAIN_MESSAGE));
        List<List> data = conn.find("PRODUITS", productId);
        List<List> TableRows = new ArrayList<>();
        TableRows.add(data.get(1));
        List TableColumns = data.get(0);
        productsTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns))); 
    }//GEN-LAST:event_searchProductMouseClicked

    private void addOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addOrderMouseClicked
        JTextField idField = new JTextField();
        JTextField clientIdField = new JTextField();
        JTextField productIdField = new JTextField();
        JTextField dateField = new JTextField();
        dateField.setText("YYYY-MM-DD");
        JTextField quantityField = new JTextField();
        JTextField priceField = new JTextField();
        JComponent[] inputs = new JComponent[] {
            new JLabel("COMMANDE_ID :"),
            idField,
            new JLabel("CLIENT_ID :"),
            clientIdField,
            new JLabel("PRODUIT_ID :"),
            productIdField,
            new JLabel("DATE_COMMANDE :"),
            dateField,
            new JLabel("QUANITTE :"),
            quantityField,
            new JLabel("PRIX_TOTAL :"),
            priceField
        };
        int result = JOptionPane.showConfirmDialog(null, inputs, "Client information", JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            conn.addOrder(Integer.parseInt(idField.getText()), Integer.parseInt(clientIdField.getText()), Integer.parseInt(productIdField.getText()), dateField.getText(), Integer.parseInt(quantityField.getText()), priceField.getText());
            updateTable("COMMANDES");
        } else {
            System.out.println("User canceled / closed the dialog, result = " + result);
        }
    }//GEN-LAST:event_addOrderMouseClicked

    private void deleteOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteOrderMouseClicked
        int index = orderTable.getSelectedRow();
        if(index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        }else {
            conn.deleteOrder((int) orderTable.getValueAt(orderTable.getSelectedRow(), 0));
            updateTable("COMMANDES");
        }
    }//GEN-LAST:event_deleteOrderMouseClicked

    private void modifyOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyOrderMouseClicked
        int index = (int) orderTable.getSelectedRow();
        if(index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            JTextField idField = new JTextField();
            idField.setText(Integer.toString((int) orderTable.getValueAt(index, 0)));
            JTextField clientIdField = new JTextField();
            clientIdField.setText(Integer.toString((int) orderTable.getValueAt(index, 1)));
            JTextField productIdField = new JTextField();
            productIdField.setText(Integer.toString((int) orderTable.getValueAt(index, 2)));
            JTextField dateField = new JTextField();
            dateField.setText((String) orderTable.getValueAt(index, 3));
            JTextField quantityField = new JTextField();
            quantityField.setText(Integer.toString((int) orderTable.getValueAt(index, 4)));
            JTextField priceField = new JTextField();
            priceField.setText((String) orderTable.getValueAt(index, 5));
            JComponent[] inputs = new JComponent[] {
                new JLabel("COMMANDE_ID :"),
                idField,
                new JLabel("CLIENT_ID :"),
                clientIdField,
                new JLabel("PRODUIT_ID :"),
                productIdField,
                new JLabel("DATE_COMMANDE :"),
                dateField,
                new JLabel("QUANITTE :"),
                quantityField,
                new JLabel("PRIX_TOTAL :"),
                priceField
            };
            int result = JOptionPane.showConfirmDialog(null, inputs, "Informations commande", JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                conn.modifyOrder(Integer.parseInt(idField.getText()), Integer.parseInt(clientIdField.getText()), Integer.parseInt(productIdField.getText()), dateField.getText(), Integer.parseInt(quantityField.getText()), priceField.getText());
                updateTable("COMMANDES");
            } else {
                System.out.println("User canceled / closed the dialog, result = " + result);
            }
        }
    }//GEN-LAST:event_modifyOrderMouseClicked

    private void searchOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchOrderMouseClicked
        int orderId = Integer.parseInt(JOptionPane.showInputDialog(null, "ID COMMANDE:", "Rechercher commande", JOptionPane.PLAIN_MESSAGE));
        List<List> data = conn.find("COMMANDES", orderId);
        List<List> TableRows = new ArrayList<>();
        TableRows.add(data.get(1));
        List TableColumns = data.get(0);
        orderTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns)));
    }//GEN-LAST:event_searchOrderMouseClicked

    private void addAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addAdminMouseClicked
        JTextField adminIdField = new JTextField();
        JPasswordField adminPasswordField = new JPasswordField();
        JComponent[] adminInputs = new JComponent[] {
            new JLabel("ID :"),
            adminIdField,
            new JLabel("Password :"),
            adminPasswordField            
        };
        int loginResult = JOptionPane.showConfirmDialog(null, adminInputs, "Admin login", JOptionPane.PLAIN_MESSAGE);
        if(loginResult == JOptionPane.OK_OPTION){
            JPasswordField passwordField = new javax.swing.JPasswordField();
            JTextField nomField = new JTextField();
            JTextField prenomField = new JTextField();
            JTextField emailField = new JTextField();
            JTextField telField = new JTextField();
            JComponent[] inputs = new JComponent[] {
                new JLabel("NOM :"),
                nomField,
                new JLabel("PRENOM :"),
                prenomField,
                new JLabel("EMAIL :"),
                emailField,
                new JLabel("PASSWORD :"),
                passwordField,
                new JLabel("TELEPHONE :"),
                telField,
            };
            int result = JOptionPane.showConfirmDialog(null, inputs, "Client information", JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                conn.addAdmin(new String(passwordField.getPassword()),nomField.getText(), prenomField.getText(), emailField.getText(), telField.getText());
                updateTable("GESTIONNAIRES");
            } else {
                System.out.println("User canceled / closed the dialog, result = " + result);
            }
        } else {
            System.out.println("Admin canceled / closed the dialog, result = " + loginResult);
        }
    }//GEN-LAST:event_addAdminMouseClicked

    private void deleteAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteAdminMouseClicked
        int index = (int) adminsTable.getSelectedRow();
        if(index == -1){
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            JTextField adminIdField = new JTextField();
            JPasswordField adminPasswordField = new JPasswordField();
            JComponent[] adminInputs = new JComponent[] {
                new JLabel("ID :"),
                adminIdField,
                new JLabel("Password :"),
                adminPasswordField            
            };
            int loginResult = JOptionPane.showConfirmDialog(null, adminInputs, "Admin login", JOptionPane.PLAIN_MESSAGE);
            if (loginResult == JOptionPane.OK_OPTION){
                int selectedAdmin = (int) adminsTable.getValueAt(adminsTable.getSelectedRow(), 0);
                conn.deleteAdmin(selectedAdmin);
                updateTable("GESTIONNAIRES");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Erreur de connexion:\nid/mot de passe incorrecte!", "Erreur", HEIGHT);
                System.out.println("User canceled / closed the dialog, result = " + loginResult);
            }
        }
    }//GEN-LAST:event_deleteAdminMouseClicked

    private void modifyAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyAdminMouseClicked
        int index = (int) adminsTable.getSelectedRow();
        if(index == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vous devez sélectionner une ligne!", "Erreur", JOptionPane.ERROR_MESSAGE);
        } else {
            JTextField adminIdField = new JTextField();
            JPasswordField adminPasswordField = new JPasswordField();
            JComponent[] adminInputs = new JComponent[] {
                new JLabel("ID :"),
                adminIdField,
                new JLabel("Password :"),
                adminPasswordField            
            };
            int loginResult = JOptionPane.showConfirmDialog(null, adminInputs, "Admin login", JOptionPane.PLAIN_MESSAGE);
            if (loginResult == JOptionPane.OK_OPTION && conn.verifyAdminPassword(new String(adminPasswordField.getPassword()), Integer.parseInt(adminIdField.getText()))){
                JPasswordField passwordField = new javax.swing.JPasswordField();
                passwordField.setText("Password");
                JTextField nomField = new JTextField();
                nomField.setText((String) adminsTable.getValueAt(index, 1));
                JTextField prenomField = new JTextField();
                prenomField.setText((String) adminsTable.getValueAt(index, 2));
                JTextField emailField = new JTextField();
                emailField.setText((String) adminsTable.getValueAt(index, 3));
                JTextField telField = new JTextField();
                telField.setText((String) adminsTable.getValueAt(index, 4));
                JComponent[] inputs = new JComponent[] {
                    new JLabel("NOM :"),
                    nomField,
                    new JLabel("PRENOM :"),
                    prenomField,
                    new JLabel("EMAIL :"),
                    emailField,
                    new JLabel("NOUVEAU MOT DE PASSE :"),
                    passwordField,
                    new JLabel("TELEPHONE :"),
                    telField,
                };
                int result = JOptionPane.showConfirmDialog(null, inputs, "Informations administrateur", JOptionPane.PLAIN_MESSAGE);
                if (result == JOptionPane.OK_OPTION) {
                    String p = new String(passwordField.getPassword());
                    conn.modifyAdmin((int) adminsTable.getValueAt(index, 0), p, nomField.getText(), prenomField.getText(), emailField.getText(), telField.getText());
                    updateTable("GESTIONNAIRES");
                } else {
                    System.out.println("User canceled / closed the dialog, result = " + result);
                }
            } else if(!conn.verifyAdminPassword(new String(adminPasswordField.getPassword()), Integer.parseInt(adminIdField.getText()))){
                javax.swing.JOptionPane.showMessageDialog(this, "Erreur de connexion:\nid/mot de passe incorrecte!", "Erreur", JOptionPane.ERROR_MESSAGE);
            } else {
                System.out.println("User canceled / closed the dialog, result = " + loginResult);
            }
        }
    }//GEN-LAST:event_modifyAdminMouseClicked

    private void searchAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchAdminMouseClicked
        int adminId = Integer.parseInt(JOptionPane.showInputDialog(null, "ID ADMIN:", "Rechercher Administrateur", JOptionPane.PLAIN_MESSAGE));
        List<List> data = conn.find("GESTIONNAIRES", adminId);
        List<List> TableRows = new ArrayList<>();
        TableRows.add(data.get(1));
        List TableColumns = data.get(0);
        adminsTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns)));
    }//GEN-LAST:event_searchAdminMouseClicked

    private void gitHubBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitHubBtnMouseEntered
        gitHubBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_gitHubBtnMouseEntered

    private void gitHubBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitHubBtnMouseExited
        gitHubBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_gitHubBtnMouseExited

    private void linkedInBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedInBtnMouseEntered
        linkedInBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_linkedInBtnMouseEntered

    private void linkedInBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedInBtnMouseExited
        linkedInBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_linkedInBtnMouseExited

    private void facebookBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookBtnMouseEntered
        facebookBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_facebookBtnMouseEntered

    private void facebookBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookBtnMouseExited
        facebookBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_facebookBtnMouseExited

    private void instagramBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramBtnMouseEntered
        instagramBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_instagramBtnMouseEntered

    private void instagramBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramBtnMouseExited
        instagramBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_instagramBtnMouseExited

    private void gitHubBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gitHubBtnMouseClicked
        String url = "https://github.com";
        try{
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_gitHubBtnMouseClicked

    private void linkedInBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_linkedInBtnMouseClicked
        String url = "https://linkedin.com";
        try{
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_linkedInBtnMouseClicked

    private void facebookBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_facebookBtnMouseClicked
        String url = "https://facebook.com";
        try{
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_facebookBtnMouseClicked

    private void instagramBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instagramBtnMouseClicked
        String url = "https://instagram.com";
        try{
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_instagramBtnMouseClicked

    private void xBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseEntered
        xBtn.setBackground(new java.awt.Color(33,63,96));
    }//GEN-LAST:event_xBtnMouseEntered

    private void xBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseExited
        xBtn.setBackground(new java.awt.Color(22,42,57));
    }//GEN-LAST:event_xBtnMouseExited

    private void xBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_xBtnMouseClicked
        String url = "https://twitter.com/";
        try{
            Desktop.getDesktop().browse(new URI(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_xBtnMouseClicked
    
    private void showPanel(String card) {
        CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, card);
    }
    
    public static synchronized DBConnect getConnexion() {
        return conn;
    }
    
    //List<> --> Object[]
    public static Object[] listToObjectArray(List list) {
        return list.toArray();
    }

    // List<List> --> Object[][]
    public static Object[][] listListToObjectArray(List<List> listList) {
        int numRows = listList.size();
        int numCols = listList.isEmpty() ? 0 : listList.get(0).size();
        Object[][] result = new Object[numRows][numCols];
        if (listList.isEmpty()) {
            result = null;
        } else {
            for (int i = 0; i < numRows; i++) {
                List innerList = listList.get(i);
                result[i] = innerList.toArray();
            }
        }
        return result;
    }
    public void updateTable(String table) {
        List<List> Data = conn.getData(table);
        List<List> TableRows = Data.subList(1, Data.size());
        List TableColumns = Data.get(0);
        switch (table) {
            case "CLIENTS" -> clientsTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns)));
            case "PRODUITS" -> productsTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns)));
            case "COMMANDES" -> orderTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns)));
            case "GESTIONNAIRES" -> adminsTable.setModel(new javax.swing.table.DefaultTableModel(listListToObjectArray(TableRows),listToObjectArray(TableColumns)));
            default -> {
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the look and feel */
        try {
            FlatLightLaf.setup();
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception e){
            e.printStackTrace();
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmin;
    private javax.swing.JButton addClient;
    private javax.swing.JButton addOrder;
    private javax.swing.JButton addProduct;
    private javax.swing.JPanel adminPnl;
    private javax.swing.JPanel adminSideBtn;
    public javax.swing.JTable adminsTable;
    private javax.swing.JPanel bg;
    private javax.swing.JPanel clientPnl;
    private javax.swing.JPanel clientSideBtn;
    public javax.swing.JTable clientsTable;
    private javax.swing.JLabel closeBtn;
    private javax.swing.JPanel crudAdmin;
    private javax.swing.JPanel crudClients;
    private javax.swing.JPanel crudOrders;
    private javax.swing.JPanel crudProducts;
    private javax.swing.JButton deleteAdmin;
    private javax.swing.JButton deleteClient;
    private javax.swing.JButton deleteOrder;
    private javax.swing.JLabel facebookBtn;
    private javax.swing.JLabel gitHubBtn;
    private javax.swing.JPanel homePnl;
    private javax.swing.JPanel homeSideBtn;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JPanel ind_5;
    private javax.swing.JLabel instagramBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel linkedInBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton modifyAdmin;
    private javax.swing.JButton modifyClient;
    private javax.swing.JButton modifyOrder;
    private javax.swing.JButton modifyProduct;
    private javax.swing.JPanel orderPnl;
    private javax.swing.JPanel orderSideBtn;
    public javax.swing.JTable orderTable;
    private javax.swing.JPanel productPnl;
    private javax.swing.JPanel productSideBtn;
    public javax.swing.JTable productsTable;
    private javax.swing.JLabel reduceBtn;
    private javax.swing.JLabel reloadAdminsTableBtn;
    private javax.swing.JLabel reloadClientsTableBtn;
    private javax.swing.JLabel reloadOrdersTableBtn;
    private javax.swing.JLabel reloadProductsTableBtn;
    private javax.swing.JButton searchAdmin;
    private javax.swing.JButton searchClient;
    private javax.swing.JButton searchOrder;
    private javax.swing.JButton searchProduct;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JPanel socialMediaPnl;
    private javax.swing.JPanel titleBar;
    private javax.swing.JLabel xBtn;
    // End of variables declaration//GEN-END:variables
}
